In [23]:
import pandas as pd
import re
import numpy as np
import category_encoders as ce

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [24]:
ddict = pd.read_excel('../Datasets/DataDictionary03.xlsx')
ddict

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,DATA DICTONARY,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,1,Car_ID,NaN,NaN,NaN,Unique id of each observation (Interger),NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,2,Symboling,NaN,NaN,NaN,"Its assigned insurance risk rating, A value of...",NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,3,carCompany,NaN,NaN,NaN,Name of car company (Categorical),NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,4,fueltype,NaN,NaN,NaN,Car fuel type i.e gas or diesel (Categorical),NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,5,aspiration,NaN,NaN,NaN,Aspiration used in a car (Categorical),NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,6,doornumber,NaN,NaN,NaN,Number of doors in a car (Categorical),NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,7,carbody,NaN,NaN,NaN,body of car (Categorical),NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,8,drivewheel,NaN,NaN,NaN,type of drive wheel (Categorical),NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,9,enginelocation,NaN,NaN,NaN,Location of car engine (Categorical),NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,10,wheelbase,NaN,NaN,NaN,Weelbase of car (Numeric),NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,11,carlength,NaN,NaN,NaN,Length of car (Numeric),NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,12,carwidth,NaN,NaN,NaN,Width of car (Numeric),NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,13,carheight,NaN,NaN,NaN,height of car (Numeric),NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,14,curbweight,NaN,NaN,NaN,The weight of a car without occupants or bagga...,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,15,enginetype,NaN,NaN,NaN,Type of engine. (Categorical),NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,16,cylindernumber,NaN,NaN,NaN,cylinder placed in the car (Categorical),NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,17,enginesize,NaN,NaN,NaN,Size of car (Numeric),NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,18,fuelsystem,NaN,NaN,NaN,Fuel system of car (Categorical),NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,19,boreratio,NaN,NaN,NaN,Boreratio of car (Numeric),NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,20,stroke,NaN,NaN,NaN,Stroke or volume inside the engine (Numeric),NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,21,compressionratio,NaN,NaN,NaN,compression ratio of car (Numeric),NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,22,horsepower,NaN,NaN,NaN,Horsepower (Numeric),NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,23,peakrpm,NaN,NaN,NaN,car peak rpm (Numeric),NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,24,citympg,NaN,NaN,NaN,Mileage in city (Numeric),NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,25,highwaympg,NaN,NaN,NaN,Mileage on highway (Numeric),NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,26,price(Dependent variable),NaN,NaN,NaN,Price of car (Numeric),NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,**Source: https://archive.ics.uci.edu/ml/datas...

In [25]:
data = pd.read_csv('../Datasets/03_CarPrice.csv')
data

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [26]:
data.isna().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    object
 3   fueltype          205 non-null    object
 4   aspiration        205 non-null    object
 5   doornumber        205 non-null    object
 6   carbody           205 non-null    object
 7   drivewheel        205 non-null    object
 8   enginelocation    205 non-null    object
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    object
 15  cylindernumber    205 non-null    object
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    object
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), object(10)
memory usage: 41.8+ KB

In [28]:
data.describe()

,car_ID,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,103.000000,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,3.329756,3.255415,10.142537,104.117073,5125.121951,25.219512,30.751220,13276.710571
std,59.322565,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,0.270844,0.313597,3.972040,39.544167,476.985643,6.542142,6.886443,7988.852332
min,1.000000,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,52.000000,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7788.000000
50%,103.000000,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,154.000000,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16503.000000
max,205.000000,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000,45400.000000

In [29]:
data['CarName'].value_counts()

CarName
peugeot 504                 6
toyota corolla              6
toyota corona               6
subaru dl                   4
mitsubishi outlander        3
                           ..
volkswagen super beetle     1
volkswagen rabbit custom    1
volvo 245                   1
volvo diesel                1
volvo 246                   1
Name: count, Length: 147, dtype: int64

In [30]:
data['aspiration'].value_counts()

aspiration
std      168
turbo     37
Name: count, dtype: int64

In [31]:
data['cylindernumber'].value_counts()

cylindernumber
four      159
six        24
five       11
eight       5
two         4
twelve      1
three       1
Name: count, dtype: int64

In [32]:
data['fuelsystem'].value_counts()

fuelsystem
mpfi    94
2bbl    66
idi     20
1bbl    11
spdi     9
4bbl     3
mfi      1
spfi     1
Name: count, dtype: int64

In [33]:
data['enginetype'].value_counts()

enginetype
ohc      148
ohcf      15
ohcv      13
dohc      12
l         12
rotor      4
dohcv      1
Name: count, dtype: int64

## Pre-processing

In [34]:
data1 = data.drop(['car_ID'], axis=1)
data1

,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,176.6,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,176.6,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,188.8,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [35]:
symboling_mapping = {-3: 3, -2: 2, -1: 1, 0: 0, 1: -1, 2: -2, 3: -3}

data1['Symboling_Categorical'] = data1['symboling'].map(symboling_mapping)

data1

,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,...,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,Symboling_Categorical
0,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,168.8,...,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0,-3
1,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,168.8,...,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0,-3
2,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,171.2,...,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0,-1
3,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,176.6,...,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0,-2
4,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,176.6,...,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0,-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,188.8,...,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0,1
201,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0,1
202,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,188.8,...,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0,1
203,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,idi,3.01,3.40,23.0,106,4800,26,27,22470.0,1
204,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0,1

In [36]:
data2 = data1.drop(['symboling'], axis=1)
data2

,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,...,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,Symboling_Categorical
0,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0,-3
1,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0,-3
2,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0,-1
3,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0,-2
4,audi 100ls,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0,-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0,1
201,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,...,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0,1
202,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0,1
203,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,idi,3.01,3.40,23.0,106,4800,26,27,22470.0,1
204,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0,1

In [37]:
test_enc = ce.OneHotEncoder(cols=['fueltype', 'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'fuelsystem'], handle_unknown='return_nan', 
                            return_df=True, use_cat_names=True)

data2

,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,...,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,Symboling_Categorical
0,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0,-3
1,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0,-3
2,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0,-1
3,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0,-2
4,audi 100ls,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0,-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0,1
201,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,...,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0,1
202,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0,1
203,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,idi,3.01,3.40,23.0,106,4800,26,27,22470.0,1
204,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0,1

In [38]:
data2_enc = test_enc.fit_transform(data2)
data2_enc

,CarName,fueltype_gas,fueltype_diesel,aspiration,doornumber_two,doornumber_four,carbody_convertible,carbody_hatchback,carbody_sedan,carbody_wagon,...,fuelsystem_spdi,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,Symboling_Categorical
0,alfa-romero giulia,1.0,0.0,std,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,3.47,2.68,9.0,111,5000,21,27,13495.0,-3
1,alfa-romero stelvio,1.0,0.0,std,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,3.47,2.68,9.0,111,5000,21,27,16500.0,-3
2,alfa-romero Quadrifoglio,1.0,0.0,std,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,2.68,3.47,9.0,154,5000,19,26,16500.0,-1
3,audi 100 ls,1.0,0.0,std,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,3.19,3.40,10.0,102,5500,24,30,13950.0,-2
4,audi 100ls,1.0,0.0,std,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,3.19,3.40,8.0,115,5500,18,22,17450.0,-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,volvo 145e (sw),1.0,0.0,std,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,3.78,3.15,9.5,114,5400,23,28,16845.0,1
201,volvo 144ea,1.0,0.0,turbo,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,3.78,3.15,8.7,160,5300,19,25,19045.0,1
202,volvo 244dl,1.0,0.0,std,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,3.58,2.87,8.8,134,5500,18,23,21485.0,1
203,volvo 246,0.0,1.0,turbo,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,3.01,3.40,23.0,106,4800,26,27,22470.0,1
204,volvo 264gl,1.0,0.0,turbo,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,3.78,3.15,9.5,114,5400,19,25,22625.0,1

In [39]:
test_enc1 = ce.OneHotEncoder(cols='CarName', handle_unknown='return_nan',
                            return_df=True, use_cat_names=True)

data2_enc1 = test_enc1.fit_transform(data2_enc)
data2_enc1

,CarName_alfa-romero giulia,CarName_alfa-romero stelvio,CarName_alfa-romero Quadrifoglio,CarName_audi 100 ls,CarName_audi 100ls,CarName_audi fox,CarName_audi 5000,CarName_audi 4000,CarName_audi 5000s (diesel),CarName_bmw 320i,...,fuelsystem_spdi,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,Symboling_Categorical
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.47,2.68,9.0,111,5000,21,27,13495.0,-3
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.47,2.68,9.0,111,5000,21,27,16500.0,-3
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.68,3.47,9.0,154,5000,19,26,16500.0,-1
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.19,3.40,10.0,102,5500,24,30,13950.0,-2
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.19,3.40,8.0,115,5500,18,22,17450.0,-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.78,3.15,9.5,114,5400,23,28,16845.0,1
201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.78,3.15,8.7,160,5300,19,25,19045.0,1
202,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.58,2.87,8.8,134,5500,18,23,21485.0,1
203,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.01,3.40,23.0,106,4800,26,27,22470.0,1
204,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.78,3.15,9.5,114,5400,19,25,22625.0,1

In [40]:
#LABEL ENCODE
le_enc_aspiration = ce.OrdinalEncoder(cols=['aspiration'], return_df=True, mapping=[{'col':'aspiration',
                                                                              'mapping':{'std':0,'turbo':1}}])

data3_enc = le_enc_aspiration.fit_transform(data2_enc1)
data3_enc

,CarName_alfa-romero giulia,CarName_alfa-romero stelvio,CarName_alfa-romero Quadrifoglio,CarName_audi 100 ls,CarName_audi 100ls,CarName_audi fox,CarName_audi 5000,CarName_audi 4000,CarName_audi 5000s (diesel),CarName_bmw 320i,...,fuelsystem_spdi,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,Symboling_Categorical
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.47,2.68,9.0,111,5000,21,27,13495.0,-3
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.47,2.68,9.0,111,5000,21,27,16500.0,-3
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.68,3.47,9.0,154,5000,19,26,16500.0,-1
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.19,3.40,10.0,102,5500,24,30,13950.0,-2
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.19,3.40,8.0,115,5500,18,22,17450.0,-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.78,3.15,9.5,114,5400,23,28,16845.0,1
201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.78,3.15,8.7,160,5300,19,25,19045.0,1
202,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.58,2.87,8.8,134,5500,18,23,21485.0,1
203,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.01,3.40,23.0,106,4800,26,27,22470.0,1
204,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.78,3.15,9.5,114,5400,19,25,22625.0,1

In [41]:
test_enc2_enginet = ce.OneHotEncoder(cols='enginetype', handle_unknown='return_nan',
                             return_df=True, use_cat_names=True)

data3_enc1 = test_enc2_enginet.fit_transform(data3_enc)
data3_enc1

,CarName_alfa-romero giulia,CarName_alfa-romero stelvio,CarName_alfa-romero Quadrifoglio,CarName_audi 100 ls,CarName_audi 100ls,CarName_audi fox,CarName_audi 5000,CarName_audi 4000,CarName_audi 5000s (diesel),CarName_bmw 320i,...,fuelsystem_spdi,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,Symboling_Categorical
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.47,2.68,9.0,111,5000,21,27,13495.0,-3
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.47,2.68,9.0,111,5000,21,27,16500.0,-3
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.68,3.47,9.0,154,5000,19,26,16500.0,-1
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.19,3.40,10.0,102,5500,24,30,13950.0,-2
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.19,3.40,8.0,115,5500,18,22,17450.0,-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.78,3.15,9.5,114,5400,23,28,16845.0,1
201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.78,3.15,8.7,160,5300,19,25,19045.0,1
202,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.58,2.87,8.8,134,5500,18,23,21485.0,1
203,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.01,3.40,23.0,106,4800,26,27,22470.0,1
204,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.78,3.15,9.5,114,5400,19,25,22625.0,1

In [42]:
#LABEL ENCODE
le_enc_cynum = ce.OrdinalEncoder(cols=['cylindernumber'], return_df=True, mapping=[{'col':'cylindernumber',
                                                                                     'mapping':{'two':0,'three':1, 'four':2, 'five':3, 'six':4, 'eight':5, 'twelve':6}},])

data4 = le_enc_cynum.fit_transform(data3_enc1)
data4

,CarName_alfa-romero giulia,CarName_alfa-romero stelvio,CarName_alfa-romero Quadrifoglio,CarName_audi 100 ls,CarName_audi 100ls,CarName_audi fox,CarName_audi 5000,CarName_audi 4000,CarName_audi 5000s (diesel),CarName_bmw 320i,...,fuelsystem_spdi,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,Symboling_Categorical
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.47,2.68,9.0,111,5000,21,27,13495.0,-3
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.47,2.68,9.0,111,5000,21,27,16500.0,-3
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.68,3.47,9.0,154,5000,19,26,16500.0,-1
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.19,3.40,10.0,102,5500,24,30,13950.0,-2
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.19,3.40,8.0,115,5500,18,22,17450.0,-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.78,3.15,9.5,114,5400,23,28,16845.0,1
201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.78,3.15,8.7,160,5300,19,25,19045.0,1
202,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.58,2.87,8.8,134,5500,18,23,21485.0,1
203,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.01,3.40,23.0,106,4800,26,27,22470.0,1
204,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.78,3.15,9.5,114,5400,19,25,22625.0,1

In [43]:
#SCALE
col_to_scale = ['wheelbase', 'carlength', 'carwidth','carheight', 'curbweight', 'enginesize', 'boreratio', 'stroke', 'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg']

stdsc = StandardScaler()

data4[col_to_scale] = stdsc.fit_transform(data4[col_to_scale])

data4

,CarName_alfa-romero giulia,CarName_alfa-romero stelvio,CarName_alfa-romero Quadrifoglio,CarName_audi 100 ls,CarName_audi 100ls,CarName_audi fox,CarName_audi 5000,CarName_audi 4000,CarName_audi 5000s (diesel),CarName_bmw 320i,...,fuelsystem_spdi,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,Symboling_Categorical
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.519071,-1.839377,-0.288349,0.174483,-0.262960,-0.646553,-0.546059,13495.0,-3
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.519071,-1.839377,-0.288349,0.174483,-0.262960,-0.646553,-0.546059,16500.0,-3
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-2.404880,0.685946,-0.288349,1.264536,-0.262960,-0.953012,-0.691627,16500.0,-1
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-0.517266,0.462183,-0.035973,-0.053668,0.787855,-0.186865,-0.109354,13950.0,-2
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-0.517266,0.462183,-0.540725,0.275883,0.787855,-1.106241,-1.273900,17450.0,-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.666445,-0.336970,-0.162161,0.250533,0.577692,-0.340094,-0.400490,16845.0,1
201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.666445,-0.336970,-0.364062,1.416637,0.367529,-0.953012,-0.837195,19045.0,1
202,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.926204,-1.232021,-0.338824,0.757535,0.787855,-1.106241,-1.128332,21485.0,1
203,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-1.183483,0.462183,3.244916,0.047732,-0.683286,0.119594,-0.546059,22470.0,1
204,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.666445,-0.336970,-0.162161,0.250533,0.577692,-0.953012,-0.837195,22625.0,1

In [46]:
data4

,CarName_alfa-romero giulia,CarName_alfa-romero stelvio,CarName_alfa-romero Quadrifoglio,CarName_audi 100 ls,CarName_audi 100ls,CarName_audi fox,CarName_audi 5000,CarName_audi 4000,CarName_audi 5000s (diesel),CarName_bmw 320i,...,fuelsystem_spdi,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,Symboling_Categorical
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.519071,-1.839377,-0.288349,0.174483,-0.262960,-0.646553,-0.546059,13495.0,-3
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.519071,-1.839377,-0.288349,0.174483,-0.262960,-0.646553,-0.546059,16500.0,-3
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-2.404880,0.685946,-0.288349,1.264536,-0.262960,-0.953012,-0.691627,16500.0,-1
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-0.517266,0.462183,-0.035973,-0.053668,0.787855,-0.186865,-0.109354,13950.0,-2
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-0.517266,0.462183,-0.540725,0.275883,0.787855,-1.106241,-1.273900,17450.0,-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.666445,-0.336970,-0.162161,0.250533,0.577692,-0.340094,-0.400490,16845.0,1
201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.666445,-0.336970,-0.364062,1.416637,0.367529,-0.953012,-0.837195,19045.0,1
202,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.926204,-1.232021,-0.338824,0.757535,0.787855,-1.106241,-1.128332,21485.0,1
203,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-1.183483,0.462183,3.244916,0.047732,-0.683286,0.119594,-0.546059,22470.0,1
204,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.666445,-0.336970,-0.162161,0.250533,0.577692,-0.953012,-0.837195,22625.0,1

In [44]:
# test_enc2_fusys = ce.OneHotEncoder(cols='fuelsystem', handle_unknown='return_nan',
#                                      return_df=True, use_cat_names=True)
# 
# data4_enc = test_enc2_fusys.fit_transform(data4)
# data4_enc

ValueError: X does not contain the columns listed in cols

In [45]:
data4.info(
    
)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Columns: 193 entries, CarName_alfa-romero giulia to Symboling_Categorical
dtypes: float64(190), int64(3)
memory usage: 309.2 KB

## Modelling

In [47]:
X = data4.drop(['price'], axis=1)
y = data4['price']

In [ ]:
X_train, y_train, X_test, y_test = train_test_split()